### ISSUE TITLE
Erro ao executar no ionic

### ISSUE THREAD

**Issue by damtaipu** [joseviniciusnunes/qrcode-pix#10]
Instalei no Ionic e ao carregar a página me mostra esse erro:

node_modules/polycrc/polycrc.js 204:16
Module parse failed: Unexpected token (204:16)
File was processed with these loaders:
 * ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js
You may need an additional loader to handle the result of these loaders.
|   }
| 
>   fromByteArray = Buffer.from.bind(Buffer)
|   fromString = Buffer.from.bind(Buffer)
| }

É possível rodar no Ionic5?

**Comment by joseviniciusnunes** [comment]
Boa tarde, é compativel com es6 ou superior, qual a versão do node?

**Comment by damtaipu** [comment]
> Boa tarde, é compativel com es6 ou superior, qual a versão do node?

Node v12.22.1

**Comment by joseviniciusnunes** [comment]
Infelizmente o ambiente do ionic não tem os recursos para gerar a validação de integridade do payload, como a lib é destinada ao backend não irei manter foco para solução deste, mas PR futuros são bem vindo para dar suporte ao front-end.
