### ISSUE TITLE
Bug ao importar lib

### ISSUE THREAD

**Issue by leomanso** [joseviniciusnunes/qrcode-pix#11]
Tenho um projeto em react, sem utilizar ts e estou tendo esse erro quando importo a lib.

./node_modules/polycrc/polycrc.js 236:16
Module parse failed: Unexpected token (236:16)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   }
| 
>   fromByteArray = Buffer.from.bind(Buffer);
|   fromString = Buffer.from.bind(Buffer);
| } // Convert most things to TypedArrays.

**Comment by joseviniciusnunes** [comment]
Olá @leomanso, a lib funciona apenas em NodeJS 12>=, o ambiente de execução da web não tem todas as features necessarias que o ambiente do node.

**Comment by leomanso** [comment]
Obrigado pelo retorno @joseviniciusnunes .

Criei uma api em node para usar a sua lib e esta funcionando de boa. O único problema que eu tive foi com espaços nos valores que passo dentro do QrCodePix(). Por exemplo:
`{
city: 'Vila Velha'
message: 'Muito obrigado!'
}`

Na hora de ler o link no app de qualquer banco dava pau. Removendo os espaçõs funcionou perfeitamente.

**Comment by joseviniciusnunes** [comment]
Bom dia @leomanso 

Fiz alguns teste com outros bancos não há nenhum decode do caracter de espaço, tem certeza que é espaço ou algum caracter especial?
