### ISSUE TITLE
Buffer is not defined

### ISSUE THREAD

**Issue by agf2000** [joseviniciusnunes/qrcode-pix#13]
Caro José,
Poderia por favor me auxiliar com o seguinte erro?

index.js:52 Uncaught (in promise) ReferenceError: Buffer is not defined
const buffer = Buffer.from(stringPayload, 'utf8');

Obrigado!

-
Ari

**Comment by altobellibm** [comment]
esse erro tá acontecendo comigo, como fez para resolver?

**Comment by joseviniciusnunes** [comment]
Boa noite meus caros

Vocês estão usando no NodeJS em backend?
