### ISSUE TITLE
[pergunta] Referência da documentação do bacen

### ISSUE THREAD

**Issue by fredguth** [joseviniciusnunes/qrcode-pix#14]
Onde fica a documentação do bacen sobre o assunto?
Poderia fazer uma explicação no Readme?
Como gerar PIX copia e cola?

**Comment by altobellibm** [comment]
Você conseguiu rodar no react com typescript?

Coloquei numa função dado a chamada de um button, ele está dando o seguinte erro:

"Uncaught ReferenceError: Buffer is not defined"

**Comment by joseviniciusnunes** [comment]
@fredguth eu sempre reviso conforme a documentação do bacen, o link do pdf do bacen está no final do readme.
o pix copia e cola você consegue com o retorno da função qrCodePix.payload()

**Comment by joseviniciusnunes** [comment]
@altobellibm não funciona no browser, não tentei gastar muito tempo com isso e recomendo que gere no backend.

Mas a limitação está na biblioteca que calcula o "dígito verificador" do payload que utilização um algoritmo específico, caso queira fazer um fazer PR eu avalio.

**Comment by fredguth** [comment]
Estou vendo a documentação, mas não sei se entendi errado, parece que deveria existir uma url https://pix.bcb.gov.br/ que não existe (ou será que era só um exemplo fictício?)

**Comment by joseviniciusnunes** [comment]
@fredguth acho que você está se referindo ao qr-code dinâmico que não está disponível para nós meros mortais, apenas para instituições financeiras, podemos criar livremente apenas qr-code estâticos que carregam no seu payload as informações para pagamento e que é o foco desta lib.

**Comment by fredguth** [comment]
Não foi o que entendi.  Veja: página 32. Pelo que entendo, podemos criar um link para um qr-code estático.  Eu entendi (e talvez esteja errado) que o bc iria disponibilizar essa url base https://pix.bcb.gov.br para guardar um conjunto oficial de apps que podem servir para fazer AppLink (app do BB, Itaú, etc).

**Comment by joseviniciusnunes** [comment]
Entendi, esse seria o pix link, os bancos tem que adaptar seus apps para que sejam chamadas por esse link que você passou, esse link não tem necessidade de ter um retorno http visto que serve apenas para chamar outro app via Deep Link.

Mas depende de que o app do banco seja compativel
