### ISSUE TITLE
Dúvida transactionId

### ISSUE THREAD

**Issue by gslima** [joseviniciusnunes/qrcode-pix#17]
Olá, não consegui tirar uma dúvida. Estou pensando em consumir este pacote, mas estou com uma dúvida referente ao pix. A transactionId é definida de forma arbitrária (se sou eu quem escolho qual o valor que deve aparecer?)?

transactionId: 'YOUR_TRANSACTION_ID'

**Comment by joseviniciusnunes** [comment]
Olá, é você que defini, é o seu identificador de transação mesmo.
