### ISSUE TITLE
Quais campos realmente são obrigatórios para a criação de um PIX?

### ISSUE THREAD

**Issue by lucascarrias** [joseviniciusnunes/qrcode-pix#18]
Primeiramente, muito obrigado por ter criado esta biblioteca!

---

Levando em consideração a [documentação da Bacen](https://www.bcb.gov.br/content/estabilidadefinanceira/pix/Regulamento_Pix/II_ManualdePadroesparaIniciacaodoPix.pdf) para geração de um **QR Code Estático**, não me parece que precisamos informar mais nada além de uma chave PIX válida.

Apesar disso a interface [QrCodePixParams](https://github.com/joseviniciusnunes/qrcode-pix/blob/master/src/index.ts#L5-L16) exige mais campos que os (aparemente) mandatórios.

```ts
interface QrCodePixParams {
    version: string;
    key: string;
    city: string;
    name: string;
    value?: number;
    transactionId?: string;
    message?: string;
    cep?: string;
    currency?: number; //default: 986 ('R$')
    countryCode?: string; //default: 'BR'
}
```

Com isso em mente, seria válido criar um QR Code levando somente com a `key`?
Se sim, poderíamos considerar a atualização da interface para o seguinte?

```ts
interface QrCodePixParams {
    version?: string; //default: "01"
    key: string;
    city?: string;
    name?: string;
    value?: number;
    transactionId?: string;
    message?: string;
    cep?: string;
    currency?: number; //default: 986 ('R$')
    countryCode?: string; //default: 'BR'
}
```

**Comment by joseviniciusnunes** [comment]
@LucasCarrias vlw mano, fico contente que esteja utilizando

a version é necessário que vc fixe no código, já que se houver uma alteração e vc atualizar a biblioteca não quebre sua aplicação.

quanto aos campos city e name por mais que o BACEN sinalize ser opcionais, alguns bancos apresentam erro se não preenchido, então recomendo que preencha para que funcione nas maiorias dos bancos possiveis.

**Comment by lucascarrias** [comment]
Obrigado pelas informações!
