### ISSUE TITLE
QR Code inválido

### ISSUE THREAD

**Issue by diegohmac** [joseviniciusnunes/qrcode-pix#19]
Estou seguindo o exemplo mostrado no [quick start](https://github.com/joseviniciusnunes/qrcode-pix#quick-start). A única coisa que alterei foi a `key` para uma chave de pix valida.

Eu consigo o `base64` porém na hora de efetuar o pagamento, só aparece QR Code inválido.

O que estou fazendo de errado?

**Comment by joseviniciusnunes** [comment]
Com qual banco está tentando, tentou com outros tbm ?

**Comment by diegohmac** [comment]
apenas Nubank

**Comment by joseviniciusnunes** [comment]
Humm, manda para mim o payload que ele gerou no meu e-mail pessoal na bio, mas recebi pagamentos essa semana inclusive Nubank, está ok.

**Comment by lipecss** [comment]
Estou tendo o mesmo problema, com nubank, pic pay, xp....

**Comment by leocastroz** [comment]
Estou utilizando a lib, porém estou com problemas no PicPay 💚

**Comment by joseviniciusnunes** [comment]
@lipecss @leocastroz montem um qrcode de teste e mandem o payload aqui fazendo favor

**Comment by joseviniciusnunes** [comment]
como não tive mais respostar vou fechar a PR

**Comment by edsonribeiro13** [comment]
Bom dia, @joseviniciusnunes reabrindo aqui, tive problema com uma chave aleatória, vou te mandar os dados:
A imagem em tela:
![image](https://github.com/joseviniciusnunes/qrcode-pix/assets/85713206/0bc071c7-6106-43c4-b8ec-19651f86216c)
O payload:
![image](https://github.com/joseviniciusnunes/qrcode-pix/assets/85713206/e2be2636-d58f-4001-b46a-30a2b2f0a0c2)

**Comment by joseviniciusnunes** [comment]
@edsonribeiro13 consegue colocar aqui o objecto js que vc montou? Se não tiver dados sensíveis

**Comment by edsonribeiro13** [comment]
Quando utilizo meu e-mail como chave funciona, porém minha cliente possui apenas essa chave aleatória e por isso gostaria de usar esta
![image](https://github.com/joseviniciusnunes/qrcode-pix/assets/85713206/abb598e3-9e8c-440e-a74b-61ac32e7f604)

**Comment by joseviniciusnunes** [comment]
@edsonribeiro13 testei aqui e funcionou
mas com uma mensagem longa como a sua não funciona, achei isso na documento do BACEN 

_**"Em outras palavras, os campos: chave, infoAdicional e fss disputam o espaço de 99 caracteres do ID raiz
(na faixa 26-51)."**_

Em resumo a chave e a mensagem se somam para validar o limite maximo de caracteres, e como a chave aleátoria tem muitos caracteres acaba limitando a mensagem, vou ajustar está validação, **mas por hora pode reduzir sua mensagem que irá funcionar.**
