### ISSUE TITLE
Error at Module Buffer

### ISSUE THREAD

**Issue by MullerHub** [joseviniciusnunes/qrcode-pix#20]
Uncaught Error: Module "buffer" has been externalized for browser compatibility. Cannot access "buffer.Buffer" in client code.
    at Object.get (browser-external:buffer:9:13)
    at createBuffer (create_buffer.js:6:52)
    at Object.result [as crc16ccitt] (define_crc.js:8:75)
    at QrCodePix (index.js:52:29)
    at index.jsx:12:19
    
    
    
    The error you are experiencing indicates that the "buffer" module has been externalized to ensure browser compatibility. The "crc16ccitt" function you are trying to access depends on the "buffer" module to work correctly, but it is not available in the browser environment.

To resolve this issue, you can use an alternative library that supports CRC16 calculations in the browser, such as the "crc-ccitt" li????

**Comment by joseviniciusnunes** [comment]
solved in https://github.com/joseviniciusnunes/qrcode-pix/pull/16, not work?
