### ISSUE TITLE
Dúvida: o que acontece após Pix ser efetuado?

### ISSUE THREAD

**Issue by dgomp** [joseviniciusnunes/qrcode-pix#21]
Olá, boa noite.

Após o Pix ser efetuado, o sistema detecta (valida), ou o QR Code continua aparecendo?

**Comment by joseviniciusnunes** [comment]
Olá @diegozl, continua  aparecendo 

Ele gera um qrcode estático, você pode usar an api do seu banco para consultar o pagamento ou gerar um qrcode dinâmico junto ao seu banco que só tem validade uma vez.
