### ISSUE TITLE
QRCode for business (CNPJ)

### ISSUE THREAD

**Issue by zkingboos** [joseviniciusnunes/qrcode-pix#22]
Can I generate a QR Code for PIX for a business using its CNPJ? I tried using a random key and CPF, which worked perfectly, but when I try using the CNPJ, the QR Code doesn't seem to be valid.

- Which banks I tried: Nubank, Banco do Brasil and PicPay. None of them worked.

**Comment by zkingboos** [comment]
Apparently, the problem was when generating the QR code because the CNPJ is longer than the CPF, it did not identify correctly and showed me as invalid. Another apparent thing is that the city cannot contain special characters.

I limited my `transactionId` to 8 characters and it worked correctly. Thank you for the help anyway 😃

**Comment by AlvaroBrasilia** [comment]
> Apparently, the problem was when generating the QR code because the CNPJ is longer than the CPF, it did not identify correctly and showed me as invalid. Another apparent thing is that the city cannot contain special characters.
> 
> I limited my `transactionId` to 8 characters and it worked correctly. Thank you for the help anyway 😃

https://github.com/joseviniciusnunes/qrcode-pix/issues/19#issuecomment-1775406673
