### ISSUE TITLE
Duvida: GUID ?

### ISSUE THREAD

**Issue by mcunha98** [joseviniciusnunes/qrcode-pix#4]
O que seria o valro de **guid: 'YOUR_GUID',** ???

**Comment by skydogtk** [comment]
Fiquei com a mesma dúvida.

**Comment by joseviniciusnunes** [comment]
Boa tarde, YOUR_GUID é uma chave personalizada que você pode criar e recuperar ela junto ao seu banco para fazer uma conciliação interna.
