### ISSUE TITLE
CRC-16 com menos do que 4 dígitos

### ISSUE THREAD

**Issue by graffitiMSX** [joseviniciusnunes/qrcode-pix#8]
Sugiro colocar ".padStart(4, '0')" no resultado da geração do crc16, peguei um caso em que gerou um número com 3 dígitos e deu erro.
Havia feito um PR mas ele foi excluído.

**Comment by joseviniciusnunes** [comment]
Bom dia @graffitiMSX 

Não me record de ter apagado alguma PR, mas pode fazer a mesma que eu realizo o merge.

**Comment by joseviniciusnunes** [comment]
Incluido na atualização 3.0.3

**Comment by graffitiMSX** [comment]
> Bom dia @graffitiMSX
> 
> Não me record de ter apagado alguma PR, mas pode fazer a mesma que eu realizo o merge.

Bom dia!

Deve ter sido algo problema na hora de criar o PR, mas vi que vc já adicionou. Obrigado :)
